micronaut:
  application:
    name: demo-devfest-micronaut
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/devfest
    driverClassName: org.postgresql.Driver
    username: postgres
    password: '${POSTGRES_PASSWORD}'
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
